// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrlwihrjbklgwblxsacz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybHdpaHJqYmtsZ3dibHhzYWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTY0OTgsImV4cCI6MjA3NDY3MjQ5OH0.aK5Iv5tqYOi5Ib_2-vJv7jO0kEwDYLFftMDo07eCJ3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});